apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-webhook-certs
  namespace: default
spec:
  secretName: {{ .Release.Name }}-webhook-certs
  dnsNames:
    - {{ .Release.Name }}-mutating-webhook.default.svc
    - {{ .Release.Name }}-mutating-webhook.default.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer
