apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-mutating-webhook
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-mutating-webhook
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-mutating-webhook
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-mutating-webhook
    namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-mutating-webhook
  apiGroup: rbac.authorization.k8s.io
